name: Build and Deploy
on:
  push:	
    branches:	
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@hexo-page

    - name: Build and Deploy
      uses: y4code/hexo-deploy-action@hexo-page
      env:
        PERSONAL_TOKEN: ${{ secrets.hexo_token }}
        PUBLISH_REPOSITORY: pupong/pupong.github.io # The repository the action should deploy to.
        BRANCH: gh-pages  # The branch the action should deploy to.
        PUBLISH_DIR: ./ # The folder the action should deploy.